clean:
	srcml test1/test1.cpp -o test1/test1.cpp.xml
	srcml test2/test2.cpp -o test2/test2.cpp.xml
	srcml test3/test3.cpp -o test3/test3.cpp.xml
	srcml test4/test4.cpp -o test4/test4.cpp.xml
	srcml test5/test5.cpp -o test5/test5.cpp.xml